dbt_best_practices:
  outputs:
    dev:
      account: ipponpartner.eu-west-1
      database: MLOPEZ_DB
      password: "{{ env_var('DBT_PASSWORD') }}"
      role: MLOPEZ_ROLE
      schema: "{{ env_var('DBT_SCHEMA') }}"
      threads: 2
      type: snowflake
      user: MLOPEZ
      warehouse: MLOPEZ_WH_XS
  target: dev
